services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - node.name=node
      - cluster.initial_cluster_manager_nodes=node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=$#j*52ocz9kP*d2ciS$jZvgo!&5ybJA39X2wpsvPOM^2WjJr
      - DISABLE_SECURITY_PLUGIN=true
      - plugins.security.ssl.http.enabled=false
      - 'DISABLE_INSTALL_DEMO_CONFIG=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
